<template>
  <div id="grid">
    <van-grid :border="false">
      <van-grid-item
        to="/dailyrecom"
        icon-prefix="my-icon"
        icon="recommend"
        text="每日推荐"
      />
      <van-grid-item
        icon-prefix="my-icon"
        to="/playlistgroup"
        icon="playlist"
        text="歌单"
      />
      <van-grid-item
        to="/personalfm"
        icon-prefix="my-icon"
        icon="fm"
        text="私人FM"
      />
      <van-grid-item
        to="/toplist"
        icon-prefix="my-icon"
        icon="toplist"
        text="排行榜"
      />
    </van-grid>
  </div>
</template>